gameobjects/particles/cParticle.cpp
gameobjects/particles/cParticle.h
gameobjects/units/cUnit.cpp
gameobjects/units/cUnit.h
include/structs.h
managers/cKeyboardManager.cpp
utils/cTimeManager.cpp
utils/common.cpp

Smoke on top of unit

---

CMakeLists.txt
drawers/cBuildingListDrawer.cpp
drawers/cUnitDrawer.cpp
gameobjects/units/cUnit.cpp
gamestates/cChooseHouseGameState.cpp
gamestates/cSetupSkirmishGameState.cpp
ini.cpp
map/cMap.h
player/brains/cPlayerBrainSkirmish.cpp
player/brains/missions/cPlayerBrainMission.cpp
player/brains/missions/cPlayerBrainMissionKindAttack.cpp
player/cPlayer.cpp
sidebar/cBuildingListUpdater.cpp
utils/cSeedMapGenerator.cpp

Next round of additional warnings.
Added some constness to a few variables in large functions too.

fix: remove unused variables

---

controls/cMouse.h
controls/mousestates/cMouseNormalState.cpp
controls/mousestates/cMouseNormalState.h
controls/mousestates/cMouseState.h

This is what I would do. What do you think?

build: update includes for cMouseNormalState

---

CMakeLists.txt
controls/cMouse.cpp
drawers/CreditsDrawer.cpp
drawers/cSideBarDrawer.cpp
gameobjects/projectiles/bullet.cpp
map/cRandomMapGenerator.cpp
player/cPlayer.cpp
player/cPlayerDifficultySettings.cpp
utils/common.cpp

A nice warning to add. It's not part of Wextra for some reason, but IMHO it helps to get clean code.

chore: eliminates useless casts

---

.github/workflows/build_cmake.yml
CMakeLists.txt
ini.cpp
player/brains/cPlayerBrainSkirmish.cpp
utils/cLog.cpp
utils/cSeedMapGenerator.cpp
utils/cSeedMapGenerator.h

I'm having fun with these extra warnings. :)
Saves us from running cppcheck or other static checkers.

remove redundant tags

---

cGame_logic.cpp
drawers/cAllegroDrawer.cpp
drawers/cAllegroDrawer.h
drawers/cMiniMapDrawer.cpp
drawers/cMiniMapDrawer.h
main.cpp
managers/cDrawManager.cpp
managers/cDrawManager.h
managers/cInteractionManager.cpp
map/cMap.cpp
map/cMap.h
utils/cTimeManager.cpp

Bugfix: Init minimapDrawer upon playing new mission

---

CMakeLists.txt
building/cItemBuilder.h
controls/mousestates/cMouseDeployState.h
controls/mousestates/cMouseNormalState.h
controls/mousestates/cMousePlaceState.h
controls/mousestates/cMouseRepairState.h
controls/mousestates/cMouseUnitsSelectedState.h
gameobjects/structures/cBarracks.h
gameobjects/structures/cConstYard.h
gameobjects/structures/cGunTurret.h
gameobjects/structures/cIx.h
gameobjects/structures/cOutPost.h
gameobjects/structures/cPalace.h
gameobjects/structures/cRefinery.h
gameobjects/structures/cSpiceSilo.h
gameobjects/structures/cStarPort.h
gameobjects/structures/cWindTrap.h
gameobjects/structures/cWor.h
gui/cGuiObject.h
managers/cInteractionManager.h
utils/cPoint.h

Another small quality/style warning.

enable -Wextra-semi warning and solve issues

---

cGame_logic.cpp
drawers/cMapDrawer.cpp
gameobjects/units/cUnit.cpp
include/definitions.h
map/cMapEditor.cpp
utils/d2tm_math.cpp
utils/d2tm_math.h

also some cleanup of math functions and includes

replace definition of pi with standard library one

---

gameobjects/particles/cParticle.cpp
gameobjects/projectiles/bullet.cpp
gameobjects/structures/cAbstractStructure.cpp
gameobjects/units/cUnit.cpp
include/definitions.h
utils/common.cpp

- keeps shadow particle for all other smoke particles

Remove shadow from smoke particle from unit

---

gameobjects/units/cUnit.cpp
include/structs.h
utils/common.cpp

Only fire twice when allowed & enough health

---

cGame_logic.cpp
gamestates/cOptionsState.h
gui/actions/cGuiActionShowOptions.cpp
gui/actions/cGuiActionShowOptions.h
gui/cGuiAction.h
managers/cDrawManager.cpp
managers/cDrawManager.h

redraw the screen as a background of the options menu without mouse cursor

---

building/cItemBuilder.cpp
cGame_logic.cpp
controls/mousestates/cMousePlaceState.cpp
drawers/cAllegroDrawer.cpp
drawers/cMiniMapDrawer.cpp
drawers/cPlaceItDrawer.cpp
gameobjects/units/cUnit.cpp
map/cMap.cpp
map/cMap.h
map/cMapCamera.cpp
map/cMapCamera.h
map/cMapEditor.cpp
utils/cPoint.h
utils/common.cpp
utils/common.h

also some header cleanup
67 fewer lines of code == fewer bugs ;)

removes some redundant functions from common.h

---

controls/mousestates/cMouseRepairState.cpp
gameobjects/units/cUnit.cpp
gameobjects/units/cUnit.h
player/brains/cPlayerBrainCampaign.cpp
player/brains/cPlayerBrainSkirmish.cpp
player/cPlayer.cpp
player/cPlayer.h

Another improvement, for #298 , in case no refinery is available to make AI retreat harvester

Harvester retreat to base when no refinery available

---

controls/cGameControlsContext.cpp
controls/cGameControlsContext.h
controls/mousestates/cMouseDeployState.cpp
controls/mousestates/cMouseNormalState.cpp
controls/mousestates/cMouseNormalState.h
controls/mousestates/cMousePlaceState.cpp
controls/mousestates/cMouseRepairState.cpp
controls/mousestates/cMouseState.cpp
controls/mousestates/cMouseState.h
controls/mousestates/cMouseUnitsSelectedState.cpp
controls/mousestates/cMouseUnitsSelectedState.h

- remember the state before repair state so that we can escape this infinite loop
- for #420

Remember when we go back into repair state again

---

cGame_logic.cpp
controls/cMouse.cpp
controls/cMouse.h
drawers/cStructureDrawer.cpp
drawers/cStructureDrawer.h
gameobjects/structures/cGunTurret.cpp
utils/d2tm_math.cpp
utils/d2tm_math.h

- use 'center' of FOV for determining the face angle, not the 'left side' of the FOV.
- fixes #443

Don't change angle too soon

---

.github/workflows/build_cmake.yml
CMakeLists.txt
dependencies/CMakeLists.txt
dependencies/alfont/CMakeLists.txt
dependencies/alfont/src/alfont.c
install_dependancies_ubuntu.sh
install_dependencies_ubuntu.sh
player/brains/superweapon/cPlayerBrainFremenSuperWeapon.cpp
sidebar/cSideBarFactory.cpp

Only contains commits about linux compilation (from #452 - which is a copy of #446)

Linux compilation support only

---

.github/workflows/build_cmake.yml
cGame_logic.cpp
controls/cMouse.cpp
controls/mousestates/cMouseNormalState.cpp
controls/mousestates/cMouseUnitsSelectedState.cpp
data/cAllegroDataRepository.cpp
drawers/cBuildingListDrawer.cpp
gameobjects/projectiles/bullet.cpp
gameobjects/structures/cStructureFactory.cpp
gameobjects/structures/cWindTrap.cpp
gamestates/cMainMenuGameState.cpp
gamestates/cSetupSkirmishGameState.cpp
include/sMouseEvent.h
managers/cInteractionManager.cpp
map/cMap.cpp
mentat/cAbstractMentat.cpp
player/brains/missions/cPlayerBrainMission.cpp
player/brains/missions/cPlayerBrainMissionKind.cpp
player/brains/missions/cPlayerBrainMissionKindAttack.cpp
player/brains/missions/cPlayerBrainMissionKindDeathHand.cpp
player/brains/missions/cPlayerBrainMissionKindExplore.cpp
player/brains/missions/cPlayerBrainMissionKindSaboteur.cpp
sidebar/cBuildingListItem.cpp
sidebar/cBuildingListUpdater.cpp
sidebar/cSideBar.cpp
utils/cSoundPlayer.cpp
utils/cStructureUtils.cpp

Cherry-picked from his PR: https://github.com/stefanhendriks/Dune-II---The-Maker/pull/446

FMT fixes by mira57

---

dependencies/alfont/CMakeLists.txt

remove double definition of ALFONT_LINUX

---

cGame_logic.cpp
drawers/CreditsDrawer.cpp
drawers/CreditsDrawer.h
drawers/cParticleDrawer.cpp
drawers/cParticleDrawer.h
gameobjects/particles/cParticle.cpp
gameobjects/particles/cParticle.h
ini.cpp
managers/cDrawManager.cpp
managers/cDrawManager.h
utils/cRectangle.cpp
utils/cRectangle.h

Bugfix #467 - wrong color options button

---

building/cItemBuilder.cpp
drawers/cMessageDrawer.cpp
drawers/cMessageDrawer.h
gameobjects/structures/cOrderProcesser.cpp
gamestates/cSelectYourNextConquestState.cpp
gamestates/cSetupSkirmishGameState.cpp
managers/cDrawManager.cpp
managers/cDrawManager.h
mentat/cProceedButtonCommand.cpp
sidebar/cSideBar.cpp

some basic cleaning, moving things around (trying to respect law of demeter).

Refactoring draw manager

---

controls/mousestates/cMouseNormalState.cpp
drawers/cMouseDrawer.cpp
drawers/cStructureDrawer.cpp
gameobjects/structures/cAbstractStructure.cpp
gameobjects/structures/cAbstractStructure.h
gameobjects/structures/cBarracks.h
gameobjects/structures/cConstYard.h
gameobjects/structures/cGunTurret.h
gameobjects/structures/cHeavyFactory.h
gameobjects/structures/cHighTech.h
gameobjects/structures/cIx.h
gameobjects/structures/cLightFactory.h
gameobjects/structures/cOutPost.h
gameobjects/structures/cPalace.h
gameobjects/structures/cRefinery.h
gameobjects/structures/cRepairFacility.h
gameobjects/structures/cRocketTurret.h
gameobjects/structures/cSpiceSilo.h
gameobjects/structures/cStarPort.h
gameobjects/structures/cWindTrap.cpp
gameobjects/structures/cWindTrap.h
gameobjects/structures/cWor.h
gameobjects/units/cUnit.cpp
gameobjects/units/cUnit.h
player/brains/cPlayerBrainCampaign.cpp
player/brains/cPlayerBrainSkirmish.cpp

depends on #478 
- ie, one 1 unit on box-select
- 1 unit specifically selected
- structure selected
for #473

Render message when unit is selected

---

cGame.h
cGame_logic.cpp
gamestates/cGameState.h
gamestates/cOptionsState.cpp
gamestates/cOptionsState.h
gamestates/cSelectMissionState.cpp
gamestates/cSelectMissionState.h
gamestates/cSelectYourNextConquestState.cpp
gamestates/cSelectYourNextConquestState.h
gui/actions/cGuiActionSelectMission.cpp
gui/actions/cGuiActionSelectMission.h
include/definitions.h
mentat/cAbstractMentat.cpp
mentat/cAbstractMentat.h
mentat/cAtreidesMentat.cpp
mentat/cBeneMentat.cpp
mentat/cButtonCommand.h
mentat/cHarkonnenMentat.cpp
mentat/cOrdosMentat.cpp

Mission Select screen

---

gameobjects/particles/cParticle.h
gameobjects/structures/cAbstractStructure.cpp
gameobjects/structures/cAbstractStructure.h
managers/cDrawManager.cpp
utils/common.cpp
utils/common.h

for #86 
plus:
- reduces the amount of smoke particles created (dampens effect the more smoke particles were created)
- fixes that you could not set rally-point for WOR & BARRACKS

Balancing - reduce repair speed

---

cGame_logic.cpp
controls/cKeyboardEvent.h
drawers/cMouseDrawer.cpp
gameobjects/structures/cOrderProcesser.cpp

Eradication of printf in several parts of the program with the power of fmt::format

Rewriting/fmt  format

---

gameobjects/projectiles/bullet.cpp
gameobjects/projectiles/bullet.h

Do not damage same-team air units

---

.github/workflows/build_master.yml
.github/workflows/build_pr.yml

- build PR's , do not produce binaries
- on `master`, build branch and produce binaries

GH Actions: PR builds & master nightly

---

src/utils/RNG.cpp
src/utils/RNG.hpp

Fix bug on random maximum limit.

Set maximum limit on RNG::rnd

---

.github/workflows/build_master.yml
.github/workflows/build_pr.yml

Test without guaranty to pass ubuntu g++ to version 14

Change on ubuntu g++ version
